### PR TITLE
Fixed bugs and added prepared for publish

### PR DESCRIPTION
**Pull request by scardinius**
The extension is ready for publish on civicrm.org :-)

### CODE REVIEW

**Comment by tttp** [comment]
Hi,

Don't put the zip, github does it automatically

**Comment by tttp** [comment]
And contact sub type is the one I wanted, the contact type is always going to be Individual, it's part of the filter ;)

**Comment by scardinius** [comment]
Ok, I'll restored contact sub type and remove zip file. 
And what about downloadUrl element in info.xml?

edit:
I already know how the archive on github works. They are creating by directory /archive and the branch name :)

**Comment by tttp** [comment]
ignore it ;)

**Comment by scardinius** [comment]
ok. The commit is ready to merge.

**Pull request merged**
